-- ResolveIT - Oracle schema
--
-- Creates the seven RESOLVE_ tables this project owns.
--
-- The Oracle schema is shared with other projects, so every table here is
-- prefixed with RESOLVE_ and every constraint name starts with resolve_.
-- Nothing in this script touches any table that is not prefixed RESOLVE_.
--
-- Run once, connected as the application's database user:
--   sqlplus -S -L 'USER/PASSWORD@//host:1521/SERVICE' @schema-oracle.sql
--
-- Tables are created parents-first because of the foreign keys.

CREATE TABLE RESOLVE_ROLE (
    role_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name  VARCHAR2(30) NOT NULL
);

CREATE TABLE RESOLVE_TEAM_SERVICE (
    team_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name     VARCHAR2(100) NOT NULL,
    service_name  VARCHAR2(120) NOT NULL,
    department    VARCHAR2(100),
    description   VARCHAR2(500)
);

CREATE TABLE RESOLVE_USER (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(100) NOT NULL,
    email          VARCHAR2(150) NOT NULL UNIQUE,
    password_hash  VARCHAR2(255) NOT NULL,
    role_id        NUMBER NOT NULL,
    team_id        NUMBER,
    CONSTRAINT fk_resolve_user_role FOREIGN KEY (role_id) REFERENCES RESOLVE_ROLE (role_id),
    CONSTRAINT fk_resolve_user_team FOREIGN KEY (team_id) REFERENCES RESOLVE_TEAM_SERVICE (team_id)
);

CREATE TABLE RESOLVE_INCIDENT (
    incident_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_code  VARCHAR2(30) NOT NULL UNIQUE,
    title          VARCHAR2(200) NOT NULL,
    description    CLOB,
    category       VARCHAR2(50),
    severity       VARCHAR2(20),
    priority       VARCHAR2(10),
    status         VARCHAR2(30),
    reported_by    NUMBER NOT NULL,
    team_id        NUMBER NOT NULL,
    root_cause     CLOB,
    resolution     CLOB,
    created_at     TIMESTAMP,
    resolved_at    TIMESTAMP,
    CONSTRAINT fk_resolve_incident_user FOREIGN KEY (reported_by) REFERENCES RESOLVE_USER (user_id),
    CONSTRAINT fk_resolve_incident_team FOREIGN KEY (team_id)     REFERENCES RESOLVE_TEAM_SERVICE (team_id)
);

CREATE TABLE RESOLVE_INCIDENT_ASSIGNMENT (
    assignment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id       NUMBER NOT NULL,
    support_user_id   NUMBER NOT NULL,
    assignment_score  NUMBER(5,2),
    assigned_at       TIMESTAMP,
    CONSTRAINT fk_resolve_assign_incident FOREIGN KEY (incident_id)     REFERENCES RESOLVE_INCIDENT (incident_id),
    CONSTRAINT fk_resolve_assign_user     FOREIGN KEY (support_user_id) REFERENCES RESOLVE_USER (user_id)
);

CREATE TABLE RESOLVE_INCIDENT_MESSAGE (
    message_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id   NUMBER NOT NULL,
    sender_id     NUMBER NOT NULL,
    message_text  CLOB,
    sent_at       TIMESTAMP,
    is_read       NUMBER(1),
    CONSTRAINT fk_resolve_message_incident FOREIGN KEY (incident_id) REFERENCES RESOLVE_INCIDENT (incident_id),
    CONSTRAINT fk_resolve_message_sender   FOREIGN KEY (sender_id)   REFERENCES RESOLVE_USER (user_id)
);

-- One row per status the incident has entered. There is deliberately no
-- OLD_STATUS, NEW_STATUS or CHANGED_BY - the previous status is simply the
-- STATUS of the previous row.
CREATE TABLE RESOLVE_INCIDENT_LOGS (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id  NUMBER NOT NULL,
    status       VARCHAR2(30),
    changed_at   TIMESTAMP,
    CONSTRAINT fk_resolve_logs_incident FOREIGN KEY (incident_id) REFERENCES RESOLVE_INCIDENT (incident_id)
);

-- Indexes on the foreign keys that are searched most often.
CREATE INDEX idx_resolve_incident_reporter ON RESOLVE_INCIDENT (reported_by);
CREATE INDEX idx_resolve_assign_incident   ON RESOLVE_INCIDENT_ASSIGNMENT (incident_id);
CREATE INDEX idx_resolve_assign_user       ON RESOLVE_INCIDENT_ASSIGNMENT (support_user_id);
CREATE INDEX idx_resolve_message_incident  ON RESOLVE_INCIDENT_MESSAGE (incident_id);
CREATE INDEX idx_resolve_logs_incident     ON RESOLVE_INCIDENT_LOGS (incident_id);
